### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by AJenbo** [pionere/d1-graphics-tool#2]
I noticed some of the changes are now landing in your master branch and there are various other changes that indicate that you might be intending to fork from upstream. Does this mean that you will no longer be submitting PRs?

**Comment by AJenbo** [comment]
@pionere just in case you don't get notifications, I sometimes don't for new repos for some reason :thinking: 

P.s. what is the TMI format that you added support for?

**Comment by pionere** [comment]
> I noticed some of the changes are now landing in your master branch and there are various other changes that indicate that you might be intending to fork from upstream. Does this mean that you will no longer be submitting PRs?

That is correct. I intend to add changes for my fork of DevilutionX. [TMI](https://github.com/pionere/devilutionX/wiki/TMI-File-Format) support is one of that. I also plan to add support for upscaled assets.
